RGBtoHex/src/main/java/ch/bbbaden/m133/firsttry/rgbtohex/RGBController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ch.bbbaden.m133.firsttry.rgbtohex;

import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Map;

public class RGBController {
    
    private static String r, g, b;

    public static void setRGB(String r, String g, String b) {
        if(r.equals("")){
            RGBController.r = "0";
        }else{
            RGBController.r = r;
        }
        
        if(g.equals("")){
            RGBController.g = "0";
        }else{
            RGBController.g = g;
        }
        
        if(b.equals("")){
            RGBController.b = "0";
        }else{
            RGBController.b = b;
        }
    }
    
    public RGBController() {
    }
    
    public static String getHex(){
        if(r == null){
            return "#FFFFFF";
        }else{
            String h_r = Integer.toHexString(Integer.parseInt(r));
            String h_g = Integer.toHexString(Integer.parseInt(g));
            String h_b = Integer.toHexString(Integer.parseInt(b));
            return "#"+r+g+b;
        }
    }
}

RGBtoHex/src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body style="background:#{index.hex}">
        <div style="width:400px;margin: 0px auto 0px auto;">
            <h:form>
                <div style="width:40%;display:inline-block;">
                    <p>Rot</p>
                    <h:inputText value="#{index.r}"></h:inputText>
                    <br />
                    <p>Gr&uuml;n</p>
                    <h:selectOneMenu value="#{index.g}">
                        <f:selectItems value="#{index.RGBValues}" />
                    </h:selectOneMenu>
                </div>
                <div style="width:20%;display:inline-block;padding-left: 30px;">
                    <p>Blau</p>
                    <h:selectOneListbox value="#{index.b}" style="height: 100px;">
                        <f:selectItems value="#{index.RGBValues}" />
                    </h:selectOneListbox>
                </div>
                <br />
                <br />
                <h:commandButton value="Senden"></h:commandButton>
            </h:form>
        </div>
    </h:body>
</html>